jobs:
  build-and-verify:
    name: Build and verify (JDK ${{ matrix.java }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Download Maven
      run: ./mvnw --version
    - continue-on-error: true
      if: ${{ matrix.java == '6'}}
      name: Set up JDK 6
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: ${{ matrix.java != '6'}}
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build and verify
      run: ./mvnw verify javadoc:javadoc site:site --batch-mode --errors --settings
        .github/workflows/settings.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - '8'
        - '11'
        - '17'
        - '21'
  publish-snapshots:
    if: github.event_name == 'push' && github.repository == 'junit-team/junit4' &&
      github.ref == 'refs/heads/main'
    name: Publish snapshot artifacts
    needs: build-and-verify
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Download Maven
      run: ./mvnw --version
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish snapshot artifacts
      run: ./mvnw deploy --batch-mode --errors --activate-profiles generate-docs --settings
        .github/workflows/settings.xml
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions:
  contents: read
